import type { Post, Platform, AnalyticsMetric, PlatformPerformance } from "./types"

export const mockPlatforms: Platform[] = [
  {
    id: "bluesky",
    name: "Bluesky",
    username: "@brand.bsky.social",
    icon: "Bird",
    connected: true,
    characterLimit: 300,
    color: "#0085ff",
  },
  {
    id: "discord",
    name: "Discord",
    username: "Not connected",
    icon: "MessageCircle",
    connected: false,
    characterLimit: 2000,
    color: "#5865F2",
  },
  {
    id: "facebook",
    name: "Facebook",
    username: "@MyBrandOfficial",
    icon: "Facebook",
    connected: true,
    characterLimit: 63206,
    color: "#1877F2",
  },
  {
    id: "flickr",
    name: "Flickr",
    username: "Not connected",
    icon: "Camera",
    connected: false,
    characterLimit: 2048,
    color: "#FF0084",
  },
  {
    id: "gettr",
    name: "Gettr",
    username: "Not connected",
    icon: "Hash",
    connected: false,
    characterLimit: 777,
    color: "#FC223B",
  },
  {
    id: "instagram",
    name: "Instagram",
    username: "@mybrand",
    icon: "Instagram",
    connected: true,
    characterLimit: 2200,
    color: "#E4405F",
  },
  {
    id: "line",
    name: "Line",
    username: "Not connected",
    icon: "MessageSquare",
    connected: false,
    characterLimit: 10000,
    color: "#00B900",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    username: "@MyBrand Company",
    icon: "Linkedin",
    connected: true,
    characterLimit: 3000,
    color: "#0A66C2",
  },
  {
    id: "mastodon",
    name: "Mastodon",
    username: "@mybrand@mastodon.social",
    icon: "Bird",
    connected: true,
    characterLimit: 500,
    color: "#6364FF",
  },
  {
    id: "medium",
    name: "Medium",
    username: "Not connected",
    icon: "FileText",
    connected: false,
    characterLimit: 20000,
    color: "#000000",
  },
  {
    id: "parler",
    name: "Parler",
    username: "Not connected",
    icon: "MessageSquare",
    connected: false,
    characterLimit: 1000,
    color: "#892434",
  },
  {
    id: "pinterest",
    name: "Pinterest",
    username: "@MyBrandPins",
    icon: "Pin",
    connected: true,
    characterLimit: 500,
    color: "#E60023",
  },
  {
    id: "quora",
    name: "Quora",
    username: "Not connected",
    icon: "HelpCircle",
    connected: false,
    characterLimit: 10000,
    color: "#B92B27",
  },
  {
    id: "reddit",
    name: "Reddit",
    username: "@MyBrand",
    icon: "Bot",
    connected: true,
    characterLimit: 40000,
    color: "#FF4500",
  },
  {
    id: "rumble",
    name: "Rumble",
    username: "@MyBrandVideo",
    icon: "Video",
    connected: true,
    characterLimit: 5000,
    color: "#85C742",
  },
  {
    id: "snapchat",
    name: "Snapchat",
    username: "Not connected",
    icon: "Ghost",
    connected: false,
    characterLimit: 250,
    color: "#FFFC00",
  },
  {
    id: "substack",
    name: "Substack",
    username: "Not connected",
    icon: "Newspaper",
    connected: false,
    characterLimit: 30000,
    color: "#FF6719",
  },
  {
    id: "telegram",
    name: "Telegram",
    username: "@mybrandchannel",
    icon: "Send",
    connected: true,
    characterLimit: 4096,
    color: "#0088cc",
  },
  {
    id: "threads",
    name: "Threads",
    username: "@mybrand",
    icon: "MessageCircle",
    connected: true,
    characterLimit: 500,
    color: "#000000",
  },
  {
    id: "tiktok",
    name: "TikTok",
    username: "@brand.official",
    icon: "Music",
    connected: true,
    characterLimit: 2200,
    color: "#000000",
  },
  {
    id: "truthsocial",
    name: "Truth Social",
    username: "Not connected",
    icon: "Flag",
    connected: false,
    characterLimit: 500,
    color: "#E81C27",
  },
  {
    id: "tumblr",
    name: "Tumblr",
    username: "@mybrand",
    icon: "Smartphone",
    connected: true,
    characterLimit: 4096,
    color: "#35465C",
  },
  {
    id: "twitch",
    name: "Twitch",
    username: "@brand_live",
    icon: "Gamepad2",
    connected: true,
    characterLimit: 500,
    color: "#9146FF",
  },
  {
    id: "twitter",
    name: "Twitter/X",
    username: "@mybrand",
    icon: "Twitter",
    connected: true,
    characterLimit: 280,
    color: "#000000",
  },
  {
    id: "vk",
    name: "VK",
    username: "Not connected",
    icon: "Flag",
    connected: false,
    characterLimit: 16384,
    color: "#0077FF",
  },
  {
    id: "viber",
    name: "Viber",
    username: "Not connected",
    icon: "Phone",
    connected: false,
    characterLimit: 7000,
    color: "#7360F2",
  },
  {
    id: "vimeo",
    name: "Vimeo",
    username: "Not connected",
    icon: "Film",
    connected: false,
    characterLimit: 5000,
    color: "#1AB7EA",
  },
  {
    id: "wechat",
    name: "WeChat",
    username: "Not connected",
    icon: "MessageCircle",
    connected: false,
    characterLimit: 10000,
    color: "#07C160",
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    username: "Not connected",
    icon: "MessageCircle",
    connected: false,
    characterLimit: 65536,
    color: "#25D366",
  },
  {
    id: "youtube",
    name: "YouTube",
    username: "@MyBrand Channel",
    icon: "Youtube",
    connected: true,
    characterLimit: 5000,
    color: "#FF0000",
  },
]

export const mockPosts: Post[] = [
  {
    id: "1",
    content: "Excited to announce our new product launch! 🚀 Stay tuned for more details. #ProductLaunch #Innovation",
    status: "scheduled",
    scheduledDate: new Date("2025-10-01T11:39:00"),
    platforms: ["twitter", "facebook", "instagram"],
    hashtags: ["ProductLaunch", "Innovation"],
    views: 152,
  },
  {
    id: "2",
    content:
      "Just finished an amazing workout session! 💪 Remember, consistency is key to success. #Fitness #Motivation",
    status: "scheduled",
    scheduledDate: new Date("2025-10-01T01:39:00"),
    platforms: ["twitter", "instagram", "tiktok", "youtube"],
    hashtags: ["Fitness", "Motivation"],
    views: 158,
  },
  {
    id: "3",
    content: "Check out our latest blog post about social media marketing strategies for 2024! Link in bio 📝",
    status: "scheduled",
    scheduledDate: new Date("2025-10-02T09:39:00"),
    platforms: ["twitter", "facebook", "linkedin", "reddit"],
    hashtags: [],
    views: 95,
  },
  {
    id: "4",
    content: "Happy Monday everyone! Let's make this week count! 🔥 #MondayMotivation #Productivity",
    status: "draft",
    platforms: ["twitter", "facebook", "instagram", "linkedin"],
    hashtags: ["MondayMotivation", "Productivity"],
    views: 82,
  },
  {
    id: "5",
    content: "Behind the scenes look at our office culture 📸 We're hiring! #WorkCulture #Jobs",
    status: "published",
    publishedDate: new Date("2025-09-29T09:39:00"),
    platforms: ["twitter", "facebook", "instagram", "linkedin"],
    hashtags: ["WorkCulture", "Jobs"],
    likes: 91155,
    comments: 1167,
    shares: 2320,
    views: 18341,
  },
]

export const mockAnalytics: AnalyticsMetric[] = [
  { label: "Total Reach", value: 91155, change: 12.5, icon: "Eye", color: "bg-blue-500" },
  { label: "Total Likes", value: 7061, change: -3.2, icon: "Heart", color: "bg-pink-500" },
  { label: "Comments", value: 1167, change: 23.7, icon: "MessageCircle", color: "bg-green-500" },
  { label: "Engagement Rate", value: 12.1, change: 5.2, icon: "BarChart3", color: "bg-purple-500" },
]

export const mockPlatformPerformance: PlatformPerformance[] = [
  { platform: "Rumble", views: 18341, engagement: 18.1, posts: 1 },
  { platform: "YouTube", views: 15234, engagement: 9.8, posts: 3 },
  { platform: "TikTok", views: 12456, engagement: 16.5, posts: 2 },
  { platform: "Instagram", views: 8324, engagement: 19.3, posts: 5 },
  { platform: "Twitch", views: 8765, engagement: 9.7, posts: 1 },
]
